### ISSUE TITLE
Default folder name?

### ISSUE THREAD

**Issue by zaszlo** [twcloud/tw5-dropbox#9]
While I didn't grant full permission I didn't get to browser for a folder to give access, once I did grant full I access I could get into my folders and select the TiddlyFile and all worked as expected. THANKS! THIS IS NEAT.
Would be nice if I could opt for not full access and still get it to work. Maybe I just should have placed the tiddlywiki file to the root folder of my dropbox? Or is there a default folder that it is looking for when I don't give full access... either way it would be worth to mention this in the README.MD.

Thanks!

**Comment by Arlen22** [comment]
When you grant Apps folder access, Dropbox creates a new folder inside the Apps folder in your Dropbox. Initially, it is empty. This is a Dropbox feature and not something that I am able to control.

**Comment by zaszlo** [comment]
Thank you, I didn't know this.
